### ISSUE TITLE
Fix concurrency issues due to i18n singleton

### ISSUE THREAD

**Issue by lucasfeliciano** [isaachinman/next-i18next#135]
We have a problem that is around since the examples of `with-i18next` on next.js repository which we should try to fix because is really bad issue.

The problem is that we have one instance of `i18next` and we pass it to the provider 

```js
<I18nextProvider
  i18n={i18n}
  initialLanguage={initialLanguage}
  initialI18nStore={initialI18nStore}
>
```

What happens here is that if a request hits the server and change the language before next renders the html it will render with the wrong language.

I solved the problem by cloning the `i18next` instance before passing to the provider

```js
...
render() {
  const clone = i18n.cloneInstance({
    initImmediate: false,
    lng: initialLanguage,
  })

  return (
    ...
    <I18nextProvider
      i18n={clone}
      initialLanguage={initialLanguage}
      initialI18nStore={initialI18nStore}
    >
    ...
  )
}
```

This also happens if you use the `i18n` instance outside of react context ( and this problem I couldn't think how to solve it yet ).
For example:

I have a file where I setup our `apollo-client` instance, and there I have some middlewares which inject some headers like this:

```js
import i18n from '../i18n' // <--- the file which exports the i18next instance
...

// Accept language link
const acceptLanguageLink = new ApolloLink((operation, forward) => {
  operation.setContext(({ headers = {} }) => {
    return {
      headers: {
        ...headers,
        'Accept-Language': i18n.language, // <--- Prone to concurrency issue
      },
    }
  })

  return forward(operation)
})
```

This issue is much more complex than looks like and I would love to think in a solution with you guys however I have some questions about the `next-18next` setup which @capellini or @isaachinman could give me some insights.

I'll start with: 
1. What is the context of `this` here: https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L12. I'm asking to know where the `i18n` comes from.

**Comment by isaachinman** [comment]
This is an interesting problem indeed.

To answer your first question: `this` at that line refers to the `NextI18Next` class instance. We are basically creating a HOC around the `app-with-translation` and [binding the entire `NextI18Next` class instance to it](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L15), to be able to access things like the `i18n` instance, and config options.

There is almost certainly a better way to do things, but this is just what I came up with as a first iteration.

As far as concurrency goes - the best way to avoid these concurrency issues is to tightly couple all SSR logic to the Express notion of a `req`. I did at one point in time consider doing something like `i18nInstances`, which would be an object (dictionary) wherein each `req` got a unique ID, and then a unique `i18n` instance assigned to it. We'd need to clean up these instances by deleting them off the `i18nInstances` object manually and so on. I'm not sure this is the best approach either, but it certainly isn't an easy problem to solve.

As soon as people start to do more complex SSR stuff outside of the strict NextJs paradigm, they're going to hit issues across the board.

**Comment by lucasfeliciano** [comment]
What we should do here is use the instance from the `req` serialize it with `req.i18n.toJSON()`  and pass through `getInitialProps`.

So we pass the serialized instance to the provider, which is the same (cloned) instance that the `i18n-express-middleware` created and use in the server

Gonna make a PR for that later.

**Comment by jamuhl** [comment]
https://github.com/isaachinman/next-i18next/issues/5#issuecomment-440384604

**Comment by isaachinman** [comment]
@jamuhl Nice to see you around here! Indeed, it looks like you predicted this one. I remember this dating back all the way to the original example in the `next-i18next` repo.

**Comment by isaachinman** [comment]
@lucasfeliciano Serialising the i18n instance is fine, but as far as I can tell that doesn't do anything to help us with the exported i18n instance from the `NextI18Next` class, and the possibility that people are going to performing actions outside the React tree (as in your Apollo case).

Any ideas about that?

**Comment by jamuhl** [comment]
@isaachinman still watching the project with joy - so active - really nice.

@lucasfeliciano another option instead of using the instance on request (req.i18n) would be not only creating a `t` function inside the `withNamespaces` that is fixed to the namespace given but also to a language -> https://www.i18next.com/overview/api#getfixedt which gets created here https://github.com/i18next/react-i18next/blob/master/src/NamespacesConsumer.js#L100

**Comment by lucasfeliciano** [comment]
@isaachinman Indeed doesn't solve the problem with the class, but on my point of view this is more related on how the next.js environment works and we should document good practices on how to use it.

The way that I solved the apollo client was the same way as the next.js example handles it:

with-apolo-client.js (HOC)
``` js
export default App => {
  return class WithData extends React.Component {
    static async getInitialProps(context) {
      const { Component, router, ctx } = context
      const { req, res } = ctx
      const apollo = initApollo(
        {},
        {
          getToken: () => req.cookies[TOKEN_COOKIE_NAME], 
          getLanguage: () => req.language, // <--- language from request injected by i18n middleware
        }
      )
      ...
      return initialProps
    }

 constructor(props) {
      super(props)
      // `getDataFromTree` renders the component first, the client is passed off as a property.
      // After that rendering is done using Next's normal rendering pipeline
      
      this.apolloClient = initApollo(props.apolloState, {
        getToken: () => cookies.getJSON(TOKEN_COOKIE_NAME),
        getLanguage: () => props.pageProps.initialLanguage,  <-- initialLanguage from the client
      })
    }
...
```

Another solution is to use cookies, since `i18n` has an option to set a cookie for the language.

And all over my application I'm now using the `i18n` instance injected by the `withNamespaces` HOC.
Which injects the instance that I serialized on my PR and passed to the provider so both on backend and frontend has the correct instance and no issue is created.

@jamuhl 
> would be not only creating a t function inside the withNamespaces that is fixed to the namespace given but also to a language

I thought about that, but that will depend on the language set on the `i18n` instance passed to the provider, if that instance is not the right one when the `withNamespaces` is called then we also have a problem

**Comment by isaachinman** [comment]
Released in v0.24.0.
