### ISSUE TITLE
Can't find i18n folder when deploying via @zeit/Now

### ISSUE THREAD

**Issue by tamer-mohamed** [isaachinman/next-i18next#462]
## Describe the bug
Tried to deploy `examples/simple` to now but failed to run.

## Occurs in next-i18next version
V1.0.0

## Steps to reproduce
- clone examples/simple
- deploy to now
-  502: BAD_GATEWAY

## Expected behaviour
it should run successfully on now platform

## Screenshots

```
ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, scandir '/var/task/static/locales/en'","code":"ENOENT","stack":["Error: ENOENT: no such file or directory, scandir '/var/task/static/locales/en'","    at Object.readdirSync (fs.js:790:3)","    at getAllNamespaces (/var/task/page.js:14724:19)","    at _default (/var/task/page.js:14729:27)","    at new NextI18Next (/var/task/page.js:17983:46)","    at Object.k7Sn (/var/task/page.js:14791:18)","    at __webpack_require__ (/var/task/page.js:23:31)","    at Module.Y0NT (/var/task/page.js:9811:63)","    at __webpack_require__ (/var/task/page.js:23:31)","    at Module.f8ve (/var/task/page.js:11600:85)","    at __webpack_require__ (/var/task/page.js:23:31)"],"errno":-2,"syscall":"scandir","path":"/var/task/static/locales/en"}
END RequestId: ba58e4b2-1a15-46d6-9693-00b1206c6973
REPORT RequestId: ba58e4b2-1a15-46d6-9693-00b1206c6973	
```
<img width="981" alt="Screenshot 2019-08-17 at 19 18 04" src="https://user-images.githubusercontent.com/4436327/63215215-c1be4880-c123-11e9-90fc-6c7173b88b7f.png">

<img width="811" alt="Screenshot 2019-08-17 at 19 18 39" src="https://user-images.githubusercontent.com/4436327/63215222-db5f9000-c123-11e9-9fff-87af92e07cdf.png">

**Comment by isaachinman** [comment]
Duplicate of #274.

**Comment by DutchPrince** [comment]
I've got the same problem

**Comment by isaachinman** [comment]
@DutchPrince I do not have knowledge about now the now platform abstracts filesystems. I would welcome any PRs. Alternatively, you can consume your localisation content via network requests with any number of `i18next` plugins.

**Comment by DutchPrince** [comment]
> @DutchPrince I do not have knowledge about now the now platform abstracts filesystems. I would welcome any PRs. Alternatively, you can consume your localisation content via network requests with any number of `i18next` plugins.

Thanks for your response!

What does PRs mean?

**Comment by isaachinman** [comment]
> What does PRs mean?

Pull requests. This is open source software and relies upon contributions from the community.

**Comment by Chill-Studio** [comment]
Excuse me guys I probably have searched for every thread that is related to this but I can't find a way to tell the server what is the path to the locales... I didn't find anything helping me in the said duplicate #274.

I am also using vercel, did anyone manage to make it work with next-i18next ?

**My locales are** located in **public/static/locales**

But when I deploy I got this path as not found

**/var/task/public/static/locales/en'**

I noticed that once deployed the structure on vercel has no public/

![Capture d’écran 2020-07-07 à 16 25 30](https://user-images.githubusercontent.com/66690474/86796138-93fd2d80-c06e-11ea-86f6-ce4f6f3f0c48.png)

I know that **"/public/static/locales"** is the default i18n path, so I tried to change it to  **/static/locales** so it will fit the vercel structure.

So I set   **localePath** to  **"static/locales"**

Then is does not deploy anymore and I got this as a path not found...

****/vercel/7d248d1f/static/**locales/en'**

I tried also the backEnd config option without success...

I am out of idea. Help :'(
 Thank you guys.

**Comment by isaachinman** [comment]
@Chill-Studio This issue needs to be resolved by the Vercel team, and they're aware of it: https://github.com/vercel/next.js/issues/13624

**Comment by Chill-Studio** [comment]
Wo that's a fast answer thank you !

Arg I can see there is not workaround :(

**Comment by isaachinman** [comment]
At the moment, the best "workaround" is to use a different serverless platform.

**Comment by limebear** [comment]
Is there any other platforms recommend?

**Comment by isaachinman** [comment]
@limebear The issue has been resolved. Vercel is probably your best option.

**Comment by anialamo** [comment]
> Excuse me guys I probably have searched for every thread that is related to this but I can't find a way to tell the server what is the path to the locales... I didn't find anything helping me in the said duplicate #274.
> 
> I am also using vercel, did anyone manage to make it work with next-i18next ?
> 
> **My locales are** located in **public/static/locales**
> 
> But when I deploy I got this path as not found
> 
> **/var/task/public/static/locales/en'**
> 
> I noticed that once deployed the structure on vercel has no public/
> 
> ![Capture d’écran 2020-07-07 à 16 25 30](https://user-images.githubusercontent.com/66690474/86796138-93fd2d80-c06e-11ea-86f6-ce4f6f3f0c48.png)
> 
> I know that **"/public/static/locales"** is the default i18n path, so I tried to change it to **/static/locales** so it will fit the vercel structure.
> 
> So I set **localePath** to **"static/locales"**
> 
> Then is does not deploy anymore and I got this as a path not found...
> 
> ****/vercel/7d248d1f/static/**locales/en'**
> 
> I tried also the backEnd config option without success...
> 
> I am out of idea. Help :'(
> Thank you guys.

@Chill-Studio did you found how to resolve this error? Can you help me please?

**Comment by isaachinman** [comment]
@anialamo Check [this repo](https://github.com/isaachinman/next-i18next-vercel). It's deployed on Vercel [here](https://next-i18next-vercel.now.sh/). Good luck!

**Comment by DutchPrince** [comment]
Thanks for this!

**Comment by samiulhsohan** [comment]
@isaachinman I am experiencing the same issue but for dynamic routes like `pages/posts/[...slug.js]`. Any idea how can I solve it? Can you please also add an example for dynamic routing on the example repo?

**Comment by musps** [comment]
@samiulhsohan Did you find any solution with dynamic routes? I'm facing the same issue

**Comment by musps** [comment]
@samiulhsohan You need add the path of your locale files

```
// next-i18next.config.jjs
const path = require('path')

module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
    localePath: path.resolve('./public/locales')
  },
};

```

**Comment by samiulhsohan** [comment]
> @samiulhsohan You need add the path of your locale files
> 
> ```
> // next-i18next.config.jjs
> const path = require('path')
> 
> module.exports = {
>   i18n: {
>     defaultLocale: "en",
>     locales: ["en", "fr"],
>     localePath: path.resolve('./public/locales')
>   },
> };
> ```

@musps  It worked! Thanks!

**Comment by LluisPitarch** [comment]
I have fixed in my case with this config:

`
//next-18next.config.js

const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es'],
    localePath: path.resolve('./public/locales'),
    defaultNS: 'app',
    serializeConfig: false,
  },
};
`

developed on Vercel i still have problems on Netlify

**Comment by nibblesnbits** [comment]
> @samiulhsohan You need add the path of your locale files
> 
> ```
> // next-i18next.config.jjs
> const path = require('path')
> 
> module.exports = {
>   i18n: {
>     defaultLocale: "en",
>     locales: ["en", "fr"],
>     localePath: path.resolve('./public/locales')
>   },
> };
> ```

I think this issue is back in recent versions (I'm on 13.2.2).  I get a warning:

```
warn  - Invalid next.config.js options detected: 
warn  -     The value at .i18n has an unexpected property, localePath, which is not in the list of allowed properties (defaultLocale, domains, localeDetection, locales).
warn  - See more info here: https://nextjs.org/docs/messages/invalid-next-config
```
And it still works locally, but not in Vercel.

**Comment by riccardolardi** [comment]
> > @samiulhsohan You need add the path of your locale files
> > ```
> > // next-i18next.config.jjs
> > const path = require('path')
> > 
> > module.exports = {
> >   i18n: {
> >     defaultLocale: "en",
> >     locales: ["en", "fr"],
> >     localePath: path.resolve('./public/locales')
> >   },
> > };
> > ```
> 
> I think this issue is back in recent versions (I'm on 13.2.2). I get a warning:
> 
> ```
> warn  - Invalid next.config.js options detected: 
> warn  -     The value at .i18n has an unexpected property, localePath, which is not in the list of allowed properties (defaultLocale, domains, localeDetection, locales).
> warn  - See more info here: https://nextjs.org/docs/messages/invalid-next-config
> ```
> 
> And it still works locally, but not in Vercel.

I think you need to move `localePath` into the exported module root scope:

```
module.exports = {
  i18n: {
    locales: ['de-CH', 'fr', 'en'],
    defaultLocale: 'de-CH',
    localeDetection: true,
  },
  localePath: path.resolve('./public/locales'),
  reloadOnPrerender: process.env.NODE_ENV === 'development',
}
```

Not sure where it's documented but it worked for me.

**Comment by adrai** [comment]
> > > @samiulhsohan You need add the path of your locale files
> > > ```
> > > // next-i18next.config.jjs
> > > const path = require('path')
> > > 
> > > module.exports = {
> > >   i18n: {
> > >     defaultLocale: "en",
> > >     locales: ["en", "fr"],
> > >     localePath: path.resolve('./public/locales')
> > >   },
> > > };
> > > ```
> > 
> > 
> > I think this issue is back in recent versions (I'm on 13.2.2). I get a warning:
> > ```
> > warn  - Invalid next.config.js options detected: 
> > warn  -     The value at .i18n has an unexpected property, localePath, which is not in the list of allowed properties (defaultLocale, domains, localeDetection, locales).
> > warn  - See more info here: https://nextjs.org/docs/messages/invalid-next-config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it still works locally, but not in Vercel.
> 
> I think you need to move `localePath` into the exported module root scope:
> 
> ```
> module.exports = {
>   i18n: {
>     locales: ['de-CH', 'fr', 'en'],
>     defaultLocale: 'de-CH',
>     localeDetection: true,
>   },
>   localePath: path.resolve('./public/locales'),
>   reloadOnPrerender: process.env.NODE_ENV === 'development',
> }
> ```
> 
> Not sure where it's documented but it worked for me.

here: https://github.com/i18next/next-i18next#vercel-and-netlify
