### ISSUE TITLE
v8. beta 6 message on the server "It seems you are using the old wait option..."

### ISSUE THREAD

**Issue by dohomi** [isaachinman/next-i18next#968]
## Describe the bug
I kickstarted a trial on the v8 beta and see following server message:
```
react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour.
```

## Occurs in next-i18next version
v8.beta6

## Steps to reproduce
Following the simple example

## Expected behaviour
Probably some more option to hide/disable the message or show an example with Suspense (even though I am not sure in NextJS environment about this)

**Comment by axmachina** [comment]
I can confirm I'm seeing this in 7.0.1

**Comment by isaachinman** [comment]
Thanks @dohomi – this is fixed by #973.

Also, you can always [pass your own `config.react` object](https://github.com/isaachinman/next-i18next/blob/next-v10/src/config/defaultConfig.ts#L27) if you want to override values.

**Comment by axmachina** [comment]
![image](https://user-images.githubusercontent.com/1904640/109100173-46a2fe80-76d9-11eb-86d1-087134b98f3e.png)

For others stumbling into here, ensure react.wait is literally undefined or it would fail.

This will result in warning/break:
`react: { wait: false, useSuspense: true }`

While this will not,
`react: { useSuspense: true }`

**Comment by isaachinman** [comment]
Hey @axmachina, v8.0.0 has been released now, and this is fixed.

**Comment by axmachina** [comment]
Note when using appWithTranslation with React Suspense as follows:

```
import { appWithTranslation } from 'next-i18next';
import React, { Component, Suspense } from "react";

const MyApp = ({ Component, pageProps }) => <Suspense fallback={"loading..."}><Component {...pageProps} /></Suspense>;

export default appWithTranslation(MyApp);
```

appWithTranslation can/will still fail as it sits outside Suspense. 

To fix, consider use this approach

```
import { appWithTranslation } from 'next-i18next';
import React, { Component, Suspense } from "react";

const MyApp = ({ Component, pageProps }) => {

const TranslatedComponent = appWithTranslation(Component);

return <Suspense fallback={"loading..."}><TranslatedComponent {...pageProps} /></Suspense>;

};

export default MyApp;
```

As well, if you wish to avoid SSR rendering, use react dynamic:

```
export default dynamic(() => Promise.resolve(MyApp), {
  ssr: false,
});
```

**Comment by spmsupun** [comment]
@isaachinman  I am getting the same message for v7, any idea?
